[book]
authors = ["aztecher"]
language = "en"
multilingual = false
src = "src/"
title = "toyvmm book (en)"

[output.html]
git-repository-url = "https://github.com/aztecher/toyvmm"
no-section-label = true
