name: Build and publish documents
on:
  push:
    branches:
    - main
    paths:
    - "ja/**"
  workflow_dispatch:
    inputs:
      ref:
        description: 'Checkout ref'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.4.10'
    - name: Build mdbook ja
      run: mdbook build ja
    - name: Deploy documents
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: aztecher/aztecher.github.io
        publish_branch: main
        publish_dir: ./ja/book
        destination_dir: ja

