name: Build and publish documents
on:
  push:
    branches:
    - main
    paths:
    - "ja/**"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.4.10'
    - name: Build mdbook ja
      run: mdbook build ja
    - name: Deploy documents
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_KEY_TOYVMM_BOOK_JA }}
        external_repository: aztecher/toyvmm-book.ja.github.io
        PUBLISH_BRANCH: main
        PUBLISH_DIR: ./ja/book
