name: Build and publish documents
on:
  push:
    branches:
    - main
    paths:
    - "en/**"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup mdbook en
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.4.10'
    - name: Build mdbook en
      run: mdbook build en
    - name: Deploy documents
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_KEY_TOYVMM_BOOK_EN }}
        external_repository: aztecher/toyvmm-book.en.github.io
        PUBLISH_BRANCH: main
        PUBLISH_DIR: ./en/book
