name: Build documents
on:
  pull_request:
    paths:
    - "src/**"
    - "book.toml"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.4.10'
    - name: Build mdBook
      run: mdbook build
