name: Build documents
on:
  pull_request:
    paths:
    - "ja/**"
    - "en/**"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.4.10'
    - name: Build mdbook ja
      run: mdbook build ja
    - name: Build mdbook en
      run: mdbook build en
