name: Build documents from workflow dispatch
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Checkout ref'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.ref }}
    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.4.10'
    - name: Build mdbook ja
      run: mdbook build ja
    - name: Build mdbook en
      run: mdbook build en
